services:
  # --- NGINX ---
  nginx:
    image: nginx:alpine
    container_name: pdf-tool_nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
       # Jeśli używasz docker-compose.dev.yml, porty są tam nadpisywane,
       # ale tutaj warto zostawić domyślne mapowanie dla jasności
       - "8098:80"
    volumes:
      # ZMIANA: Mapujemy lokalny folder ./outputs do kontenera
      - ./outputs:/var/www/pdf_downloads

  # --- BACKEND ---
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pdf-tool_backend
    volumes:
      # ZMIANA: Ten sam folder ./outputs mapujemy do backendu
      - ./outputs:/app/outputs
      - ./server/fonts:/app/fonts

  # --- FRONTEND ---
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pdf-tool_frontend

networks:
  default:
    name: pdf-tool-network