services:
  nginx:
    image: nginx:alpine
    container_name: pdf-tool_nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
       - "8098:80"
    volumes:
      # Nginx czyta z lokalnego ./outputs
      - ./outputs:/var/www/pdf_downloads

  # --- BACKEND ---
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pdf-tool_backend
    volumes:
      - ./outputs:/data/outputs
      - ./server/fonts:/app/fonts

  # --- FRONTEND ---
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pdf-tool_frontend

networks:
  default:
    name: pdf-tool-network