server {
    listen 80;

    # 1. Frontend (Static Files)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Obsługa routingu Reacta (SPA)
    }

    # 2. Backend API
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        client_max_body_size 50M;
    }

    # 3. Downloads
    location /downloads/ {
        alias /var/www/pdf_downloads/;
        autoindex off;
    }
}